# Generated by Django 5.0 on 2025-01-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_testimonial_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
